(function(w,i){function d(b,p,v){var n=-1,l=I.call(arguments,0);b=o[D.$name]||{};p=[];for(v=true;l[++n];)if(z.toType(l[n])==="boolean")v=l[n];else z.toType(l[n])==="object"&&p.push(l[n]);if(p.length>=2)b=p.splice(0,1)[0];for(n=0;n<p.length;n++){l=p[n];for(var y in l)if(!b.hasOwnProperty(y)||v)b[y]=l[y]}return b}function h(b,p){var v=b.split("."),n=-1,l=o;if(v[0]=="")v[0]=D.$name;for(;v[++n];){if(l[v[n]]===i)l[v[n]]={};l=l[v[n]]}p&&p.call(l,o[D.$name])}var o=this,D={$name:"Leta",$version:0.1,$root:this},
K=-1,E=Object.prototype,I=Array.prototype.slice,A=E.toString,C=E.hasOwnProperty;E=Array.isArray;var z={};z.isUndefined=function(b){return b===void 0};z.isNull=function(b){return b===null};z.isArray=E||function(b){return A.call(b)==="[object Array]"};z.isPlainObject=function(b){var p;if(!b||A.call(b)!=="[object Object]"||!("isPrototypeOf"in b)||!C.call(b,"constructor")&&!C.call(b.constructor.prototype,"isPrototypeOf"))return false;for(p in b)return p===i||C.call(b,p)};z.isEmpty=function(b){if(z.isArray(b)||
z.isString(b))return b.length===0;for(var p in b)if(C.call(b,p))return false;return true};z.isString=function(b){return!!(b===""||b&&b.charCodeAt&&b.substr)};z.isObject=function(b){return b===Object(b)};z.isElement=function(b){return!!(b&&b.nodeType===1)};z.isArguments=function(b){return!!(b&&C.call(b,"callee"))};z.isFunction=function(b){return!!(b&&b.constructor&&b.call&&b.apply)};z.isNaN=function(b){return b!==b};z.isNumber=function(b){return!!(b===0||b&&b.toFixed&&b.toExponential)};z.isBoolean=
function(b){return b===false||b===true};z.isRegExp=function(b){return!!(b&&b.test&&b.exec&&(b.ignoreCase||b.ignoreCase===false))};z.$SCRIPTNODE=function(){var b=document.getElementsByTagName("script");return b[b.length-1]}();z.$LETA$=++K;z.toType=function(b){return function(p){if(p===b)return"global";return A.call(p).match(/\s([a-z|A-Z]+)/)[1].toLowerCase()}}(this);var m=function(b,p,v){function n(U){var k=U;if(U&&U.substring(0,4)=="url(")k=U.substring(4,U.length-1);return!m.registered[k]&&(!m.__checkURLs||
!m.__checkURLs[k])&&U&&U.length>4&&U.substring(0,4)=="url("}var l=-1,y=[];if(z.isArray(b)){l=b;for(var H=0;H<l.length;H++)if(m.registered[l[H]]||n(l[H]))y.push(l[H]);b=y[0];l=1}else for(;typeof arguments[++l]=="string";)if(m.registered[b]||n(b))y.push(arguments[l]);p=arguments[l];v=arguments[++l];if(y.length>1){var S=p;p=function(){m(y,S,v)}}l=m.registered[b];if(!m.__checkURLs)m.__checkURLs={};if(n(b)&&b.substring(0,4)=="url("){b=b.substring(4,b.length-1);if(!m.__checkURLs[b]){y[0]=b;m.register(b,
b);l=m.registered[b];H=m.prototype.getCallbackQueue(b);var N=new m.prototype.curCallBack(function(){m.__checkURLs[b]=true});H.push(N);H.push(new m.prototype.curCallBack(p,v));v=p=i}}if(l){for(H=l.requirements.length-1;H>=0;H--)if(m.registered[l.requirements[H].name]){m(l.requirements[H].name,function(){m(b,p,v)},v);return}for(H=0;H<l.urls.length;H++)if(H==l.urls.length-1)p?m.load(l.name,l.urls[H],l.isAsyn,l.asyncWait,new m.prototype.curCallBack(p,v)):m.load(l.name,l.urls[H],l.isAsyn,l.asyncWait);
else m.load(l.name,l.urls[H],l.isAsyn,l.asyncWait)}else p&&p.call(v)};m.prototype={register:function(b,p,v,n){if(z.isObject(b)){p=b;p=new m.prototype.__register(p.name,p.isAsyn,p.asyncWait,n)}else p=new m.prototype.__register(b,p,v,n);if(!m.registered)m.registered={};m.registered[b]&&window.console&&window.console.log('Warning: Module named "'+b+'" was already registered, Overwritten!!!');return m.registered[b]=p},__register:function(b,p,v){this.name=b;var n=0,l=arguments[++n];if(l&&typeof l=="boolean"){this.isAsyn=
l;l=arguments[++n]}else this.isAsyn=true;this.asyncWait=l&&typeof l=="number"?v:0;this.urls=[];if(l&&l.length&&typeof l!="string")this.urls=l;else for(n=n;n<arguments.length;n++)arguments[n]&&typeof arguments[n]=="string"&&this.urls.push(arguments[n]);this.requirements=[];this.require=function(y){this.requirements.push({name:y});return this};this.register=function(y,H,S,N){return m.register(y,H,S,N)};return this},defaultAsyncTime:10,load:function(b,p,v,n,l){if(n==i)n=m.defaultAsyncTime;if(!m.loadedscripts)m.loadedscripts=
[];var y=m.prototype.getCallbackQueue(p);y.push(new m.prototype.curCallBack(function(){m.loadedscripts.push(m.registered[b]);m.registered[b]=i},null));if(l){y.push(l);if(y.length>2)return}v?m.asynLoadScript(p,n,y):m.xhrLoadScript(b,p,y)},xhrLoadScript:function(b,p,v){var n;if(window.XMLHttpRequest)n=new XMLHttpRequest;else if(window.ActiveXObject)n=new ActiveXObject("Microsoft.XMLHTTP");n.onreadystatechange=function(){if(n.readyState==4&&n.status==200){m.injectScript(n.responseText,b);if(v)for(var l=
0;l<v.length;l++)v[l].runCallback();m.__callbackQueue[p]=i}};v.length>1?n.open("GET",p,true):n.open("GET",p,false);n.send(null)},asynLoadScript:function(b,p,v){var n=m.prototype.createScriptNode();n.setAttribute("src",b);if(v){var l=function(){m.__callbackQueue[b]=i;for(var y=0;y<v.length;y++)v[y].runCallback();v=[]};n.onload=n.onreadystatechange=function(){if(!n.readyState||n.readyState=="loaded"||n.readyState=="complete"||n.readyState==4&&n.status==200)p>0?setTimeout(l,p):l()}}document.getElementsByTagName("head")[0].appendChild(n)},
curCallBack:function(b,p){this.callback=b;this.context=p;this.runCallback=function(){this.callback&&(this.context?this.callback.call(this.context):this.callback())}},getCallbackQueue:function(b){if(!m.__callbackQueue)m.__callbackQueue={};var p=m.__callbackQueue[b];p||(p=m.__callbackQueue[b]=[]);return p},createScriptNode:function(){var b=document.createElement("script");b.setAttribute("type","text/javascript");b.setAttribute("language","Javascript");return b},injectScript:function(b,p){var v=m.prototype.createScriptNode();
try{v.setAttribute("name",p)}catch(n){}v.text=b;document.getElementsByTagName("head")[0].appendChild(v)}};m.register=m.prototype.register;m.load=m.prototype.load;m.defaultAsyncTime=m.prototype.defaultAsyncTime;m.asynLoadScript=m.prototype.asynLoadScript;m.xhrLoadScript=m.prototype.xhrLoadScript;K={module:m,multiModule:function(b,p,v){var n=-1,l=0,y=[];if(z.isArray(b))y=b;else{for(;z.isString(arguments[++n]);)y.push(arguments[n]);p=arguments[n];v=arguments[++n]}n=0;for(var H=y.length;n<H;n++)m(y[n],
function(){l++;l==y.length&&p&&p.call(v)})},extend:d,mix:d,register:h,NS:h};var Q=z.isUndefined(Q)?d({},D,z,K):o[D.$name];this[D.$name]=w[D.$name]=Q;Q.module.register(D.$name,Q.$SCRIPTNODE.src)})(window);
(function(){function w(E){return h.call(K(E)?E:function(){},E,1)}function i(E,I,A){for(var C in I)if(I.hasOwnProperty(C))E[C]=K(I[C])&&K(A.prototype[C])&&D.test(I[C])?d(C,I[C],A):I[C]}function d(E,I,A){return function(){var C=this._super;this._super=A.prototype[E];var z=I.apply(this,arguments);this._super=C;return z}}function h(E,I){function A(){}function C(){if(this.initialize)this.initialize.apply(this,arguments);else{I||K(E)&&z.apply(this,arguments);Q.apply(this,arguments)}}A.prototype=this.prototype;
var z=this,m=new A,Q=K(E)?E:this,b=K(E)?{}:E;C.methods=function(p){i(m,p,z);C.prototype=m;return this};C.methods.call(C,b).prototype.constructor=C;C.extend=arguments.callee;C.prototype.implement=w.statics=function(p,v){p=o.toType(p)==="string"?function(){var n={};n[p]=v;return n}():p;i(this,p,z);return this};return C}var o=this.Leta,D=/'leta'/.test(function(){})?/\b_super\b/:/.*/,K=function(E){return o.toType(E)=="function"&&E.apply&&E.call};Leta.extend({Class:w})})(window);
(function(w){var i={},d=Array.prototype,h=Object.prototype.hasOwnProperty,o=d.forEach,D=d.map,K=d.every,E=d.some,I=d.indexOf;i.each=i.forEach=function(A,C,z){if(!w.isNull(A))if(o&&A.forEach===o)A.forEach(C,z);else if(A.length===+A.length)for(var m=0,Q=A.length;m<Q;m++){if(C.call(z,A[m],m,A)===false)break}else for(m in A)if(h.call(A,m))if(C.call(z,A[m],m,A)===false)break};i.map=function(A,C,z){var m=[];if(D&&A.map===D)return A.map(C,z);i.each(A,function(Q,b,p){m[m.length]=C.call(z,Q,b,p)});return m};
i.every=i.all=function(A,C,z){if(K&&A.every===K)return A.every(C,z);i.each(A,function(m,Q,b){if(!C.call(z,m,Q,b))return false});return true};i.some=i.any=function(A,C,z){var m=false;if(E&&A.some===E)return A.some(C,z);i.each(A,function(Q,b,p){if(m|=C.call(z,Q,b,p))return m});return m};i.contains=i.include=function(A,C){var z=false;if(I&&A.indexOf===I)return A.indexOf(C)!=-1;i.any(A,function(m){if(z=m===C)return true});return z};w.extend({array:i})})(Leta);
(function(){var w={};w.clone=function(i){var d;if(Leta.isArray(i)){d=[];for(var h=0,o=0,D=i.length;o<D;o++)d[h++]=w.clone(i[o])}else if(Leta.isPlainObject(i)){d={};for(h in i)if(i.hasOwnProperty(h))d[h]=w.clone(i[h])}else d=i;return d};w.each=w.forEach=function(i,d){var h,o;if(Leta.isFunction(d))for(o in i)if(i.hasOwnProperty(o)){h=i[o];h=d.call(i,h,o);if(h===false)break}return i};w.map=function(i,d){var h,o={};if(Leta.isFunction(d))for(h in i)if(i.hasOwnProperty(h))o[h]=d(i[h],h);return o};w.extend=
function(i,d,h){if(Leta.isUndefined(h))h=true;for(var o in d)if(!i.hasOwnProperty(o)||h)i[o]=d[o];return i};w.deepExtend=function(i,d,h){if(Leta.isUndefined(h))h=true;for(var o in d)if(Leta.isPlainObject(d[o])&&Leta.isPlainObject(i[o]))w.deepExtend(i[o],d[o],h);else if(!i.hasOwnProperty(o)||h)i[o]=d[o];return i};Leta.extend({object:w})})();
Leta.register(".str",function(){var w=this;this.escape=function(h){return(""+h).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")};this.templateSettings={evaluate:/<%([\s\S]+?)%>/g,interpolate:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};var i=/.^/,d=function(h){return h.replace(/\\\\/g,"\\").replace(/\\'/g,"'")};this.template=function(h,o){var D=w.templateSettings;D="var __p=[],print=function(){__p.push.apply(__p,arguments);};with(obj||{}){__p.push('"+
h.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(D.escape||i,function(E,I){return"',$.escape("+d(I)+"),'"}).replace(D.interpolate||i,function(E,I){return"',"+d(I)+",'"}).replace(D.evaluate||i,function(E,I){return"');"+d(I).replace(/[\r\n\t]/g," ")+";__p.push('"}).replace(/\r/g,"\\r").replace(/\n/g,"\\n").replace(/\t/g,"\\t")+"');}return __p.join('');";var K=new Function("obj","$",D);if(o)return K(o,w);return function(E){return K.call(this,E,w)}}});
(function(w){var i={init:function(){this.browser=this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS";this.UA=navigator.userAgent.toLowerCase()},searchString:function(d){for(var h=0;h<d.length;h++){var o=d[h].string,D=d[h].prop;this.versionSearchString=d[h].versionSearch||d[h].identity;if(o){if(o.indexOf(d[h].subString)!=
-1)return d[h].identity}else if(D)return d[h].identity}},searchVersion:function(d){var h=d.indexOf(this.versionSearchString);if(h!=-1)return parseFloat(d.substring(h+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera"},{string:navigator.vendor,
subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",
identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};i.init();w.extend({browser:{name:i.browser,version:i.version,msie:i.browser==="Explorer",chorme:i.browser==="Chrome",firefox:i.browser==="Firefox",safari:i.browser==="Safari",opera:i.browser===
"Opera"},OS:{name:i.OS,isTouchDevice:/andriod|iphone|ipad/.test(i.UA)}})})(Leta);
(function(w,i){function d(){this.c={}}function h(e){return Z.g(e)||Z.s(e,"(^|\\s+)"+e+"(\\s+|$)",1)}function o(e,s){for(var r=0,J=e.length;r<J;r++)s(e[r])}function D(e){for(var s=[],r=0,J=e.length;r<J;++r)v(e[r])?s=s.concat(e[r]):s[s.length]=e[r];return s}function K(e){for(var s=0,r=e.length,J=[];s<r;s++)J[s]=e[s];return J}function E(e){for(;e=e.previousSibling;)if(e[f]==1)break;return e}function I(e){return e.match(W)}function A(e,s,r,J,F,R,Y,$,X,ca,ia){var la,ha,ma;if(this[f]!==1)return false;if(s&&
s!=="*"&&this[g]&&this[g].toLowerCase()!==s)return false;if(r&&(la=r.match(q))&&la[1]!==this.id)return false;if(r&&(ma=r.match(x)))for(e=ma.length;e--;)if(!h(ma[e].slice(1)).test(this.className))return false;if(X&&y.pseudos[X]&&!y.pseudos[X](this,ia))return false;if(J&&!Y){X=this.attributes;for(ha in X)if(Object.prototype.hasOwnProperty.call(X,ha)&&(X[ha].name||ha)==F)return this}if(J&&!z(R,j(this,F)||"",Y))return false;return this}function C(e){return ka.g(e)||ka.s(e,e.replace(fa,"\\$1"))}function z(e,
s,r){switch(e){case "=":return s==r;case "^=":return s.match(aa.g("^="+r)||aa.s("^="+r,"^"+C(r),1));case "$=":return s.match(aa.g("$="+r)||aa.s("$="+r,C(r)+"$",1));case "*=":return s.match(aa.g(r)||aa.s(r,C(r),1));case "~=":return s.match(aa.g("~="+r)||aa.s("~="+r,"(?:^|\\s+)"+C(r)+"(?:\\s+|$)",1));case "|=":return s.match(aa.g("|="+r)||aa.s("|="+r,"^"+C(r)+"(-|$)",1))}return 0}function m(e,s){var r=[],J=[],F,R,Y,$,X,ca=s,ia=a.g(e)||a.s(e,e.split(da)),la=e.match(ba);if(!ia.length)return r;R=(ia=ia.slice(0)).pop();
if(ia.length&&(F=ia[ia.length-1].match(G)))ca=l(s,F[1]);if(!ca)return r;$=I(R);Y=ca!==s&&ca[f]!==9&&la&&/^[+~]$/.test(la[la.length-1])?function(ha){for(;ca=ca.nextSibling;)ca[f]==1&&($[1]?$[1]==ca[g].toLowerCase():1)&&(ha[ha.length]=ca);return ha}([]):ca[k]($[1]||"*");F=0;for(R=Y.length;F<R;F++)if(X=A.apply(Y[F],$))r[r.length]=X;if(!ia.length)return r;o(r,function(ha){if(Q(ha,ia,la))J[J.length]=ha});return J}function Q(e,s,r,J){function F(Y,$,X){for(;X=ja[r[$]](X,Y);)if(b(X)&&A.apply(X,I(s[$])))if($){if(R=
F(X,$-1,X))return R}else return X}var R;return(R=F(e,s.length-1,e))&&(!J||c(R,J))}function b(e,s){return e&&typeof e==="object"&&(s=e[f])&&(s==1||s==9)}function p(e){var s=[],r,J;r=0;a:for(;r<e.length;++r){for(J=0;J<s.length;++J)if(s[J]==e[r])continue a;s[s.length]=e[r]}return s}function v(e){return typeof e==="object"&&isFinite(e.length)}function n(e){if(!e)return S;if(typeof e=="string")return y(e)[0];if(!e[f]&&v(e))return e[0];return e}function l(e,s,r){return e[f]===9?e.getElementById(s):e.ownerDocument&&
((r=e.ownerDocument.getElementById(s))&&c(r,e)&&r||!c(e,e.ownerDocument)&&t('[id="'+s+'"]',e)[0])}function y(e,s){var r,J,F=n(s);if(!F||!e)return[];if(e===window||b(e))return!s||e!==window&&b(F)&&c(e,F)?[e]:[];if(e&&v(e))return D(e);if(r=e.match(V)){if(r[1])return(J=l(F,r[1]))?[J]:[];if(r[2])return K(F[k](r[2]));if(u&&r[3])return K(F[U](r[3]))}return t(e,F)}function H(e,s){return function(r){var J,F;if(O.test(r)){if(e[f]!==9){if(!(F=J=e.getAttribute("id")))e.setAttribute("id",F="__$qsameupscotty");
r='[id="'+F+'"]'+r;s(e.parentNode||e,r,true);J||e.removeAttribute("id")}}else r.length&&s(e,r,false)}}var S=document,N=S.documentElement,U="getElementsByClassName",k="getElementsByTagName",g="tagName",f="nodeType",t,q=/#([\w\-]+)/,x=/\.[\w\-]+/g,G=/^#([\w\-]+)$/,L=/^([\w]+)?\.([\w\-]+)$/,O=/(^|,)\s*[>~+]/,T=/^\s+|\s*([,\s\+\~>]|$)\s*/g,ea=/[\s\>\+\~]/,ga=/(?![\s\w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,fa=/([.*+?\^=!:${}()|\[\]\/\\])/g,V=RegExp(G.source+"|"+/^([\w\-]+)$/.source+
"|"+/^\.([\w\-]+)$/.source),ba=RegExp("("+ea.source+")"+ga.source,"g"),da=RegExp(ea.source+ga.source),W=RegExp(/^(\*|[a-z0-9]+)?(?:([\.\#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*\~]?\=)['"]?([ \w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),ja={" ":function(e){return e&&e!==N&&e.parentNode},">":function(e,s){return e&&e.parentNode==s.parentNode&&e.parentNode},"~":function(e){return e&&e.previousSibling},"+":function(e,
s,r,J){if(!e)return false;return(r=E(e))&&(J=E(s))&&r==J&&r}};d.prototype={g:function(e){return this.c[e]||i},s:function(e,s,r){s=r?RegExp(s):s;return this.c[e]=s}};var Z=new d,ka=new d,aa=new d,a=new d,c="compareDocumentPosition"in N?function(e,s){return(s.compareDocumentPosition(e)&16)==16}:"contains"in N?function(e,s){s=s[f]===9||s==window?N:s;return s!==e&&s.contains(e)}:function(e,s){for(;e=e.parentNode;)if(e===s)return 1;return 0},j=function(){var e=S.createElement("p");return(e.innerHTML='<a href="#x">x</a>')&&
e.firstChild.getAttribute("href")!="#x"?function(s,r){return r==="class"?s.className:r==="href"||r==="src"?s.getAttribute(r,2):s.getAttribute(r)}:function(s,r){return s.getAttribute(r)}}(),u=!!S[U],B=S.querySelector&&S.querySelectorAll,P=function(e,s){var r=[],J,F;try{if(s[f]===9||!O.test(e))return K(s.querySelectorAll(e));o(J=e.split(","),H(s,function(Y,$){F=Y.querySelectorAll($);if(F.length==1)r[r.length]=F.item(0);else if(F.length)r=r.concat(K(F))}));return J.length>1&&r.length>1?p(r):r}catch(R){}return M(e,
s)},M=function(e,s){var r=[],J,F,R,Y;e=e.replace(T,"$1");if(J=e.match(L)){Y=h(J[2]);J=s[k](J[1]||"*");F=0;for(R=J.length;F<R;F++)if(Y.test(J[F].className))r[r.length]=J[F];return r}o(J=e.split(","),H(s,function($,X,ca){Y=m(X,$);F=0;for(R=Y.length;F<R;F++)if($[f]===9||ca||c(Y[F],s))r[r.length]=Y[F]}));return J.length>1&&r.length>1?p(r):r};ea=function(e){if(typeof e.useNativeQSA!=="undefined")t=!e.useNativeQSA?M:B?P:M};ea({useNativeQSA:true});y.configure=ea;y.uniq=p;y.is=function(e,s,r){if(b(s))return e==
s;if(v(s))return!!~D(s).indexOf(e);for(var J=s.split(","),F;s=J.pop();){F=a.g(s)||a.s(s,s.split(da));s=s.match(ba);F=F.slice(0);if(A.apply(e,I(F.pop()))&&(!F.length||Q(e,F,s,r)))return true}return false};y.pseudos={};if(w.Leta)w.Leta.extend({$qsa:y,$get:y});else this.$qsa=qsa;return y})(window);
(function(){function w(a,c,j){for(var u=0,B=a.length;u<B;u++)c.call(j||a[u],a[u],u,a);return a}function i(a,c,j){for(var u=0,B=a.length;u<B;u++)if(a[u]&&a[u].nodeName&&a[u].nodeType==1){i(a[u].childNodes,c,j);c.call(j||a[u],a[u],u,a)}return a}function d(a){return a.replace(/-(.)/g,function(c,j){return j.toUpperCase()})}function h(a){a[V]("data-node-uid")||a[fa]("data-node-uid",++T);uid=a[V]("data-node-uid");return O[uid]||(O[uid]={})}function o(a){(uid=a[V]("data-node-uid"))&&delete O[uid]}function D(a,
c){try{return a===null||a===undefined?undefined:a==="true"?true:a==="false"?false:a==="null"?null:(c=parseFloat(a))==a?c:a}catch(j){}}function K(a,c,j,u,B){u=0;for(B=a.length;u<B;++u)if(c.call(j,a[u],u,a))return true;return false}function E(a){a=="transform"&&(a=ba.transform)||/^transform-?[Oo]rigin$/.test(a)&&(a=ba.transform+"Origin")||a=="float"&&(a=ba.cssFloat);return a?d(a):null}function I(a,c,j){var u=0,B=c||this,P=[];a=y&&typeof a=="string"&&a.charAt(0)!="<"?y(a):a;w(z(a),function(M){w(B,function(e){var s=
!e[l]||e[l]&&!e[l][l]?function(){var r=e.cloneNode(true),J,F;if(B.$&&B.cloneEvents){B.$(r).cloneEvents(e);J=B.$(r).find("*");F=B.$(e).find("*");for(var R=0;R<F.length;R++)B.$(J[R]).cloneEvents(F[R])}return r}():e;j(M,s);P[u]=s;u++})},this);w(P,function(M,e){B[e]=M});B.length=u;return B}function A(a,c){return typeof c=="function"?c(a):c}function C(a){this.length=0;if(a){a=typeof a!=="string"&&!a.nodeType&&typeof a.length!=="undefined"?a:[a];this.length=a.length;for(var c=0;c<a.length;c++)this[c]=a[c]}}
function z(a){return typeof a=="string"?b.create(a):a&&a.nodeName&&a.nodeType==1?[a]:a}function m(a,c,j){var u=this[0];if(!u)return this;if(a==null&&c==null)return(Q(u)?{x:p.pageXOffset||n.scrollLeft,y:p.pageYOffset||n.scrollTop}:{x:u.scrollLeft,y:u.scrollTop})[j];if(Q(u))p.scrollTo(a,c);else{a!=null&&(u.scrollLeft=a);c!=null&&(u.scrollTop=c)}return this}function Q(a){return a===p||/^(?:body|html)$/i.test(a.tagName)}function b(a,c){return new C(a,c)}var p=window,v=p.document,n=v.documentElement,l=
"parentNode",y=null,H=/^(checked|value|selected)$/i,S=/^(select|fieldset|table|tbody|tfoot|td|tr|colgroup)$/i,N=["<table>","</table>",1],U=["<table><tbody><tr>","</tr></tbody></table>",3],k=["<select>","</select>",1],g=["_","",0,1],f={thead:N,tbody:N,tfoot:N,colgroup:N,caption:N,tr:["<table><tbody>","</tbody></table>",2],th:U,td:U,col:["<table><colgroup>","</colgroup></table>",2],fieldset:["<form>","</form>",1],legend:["<form><fieldset>","</fieldset></form>",2],option:k,optgroup:k,script:g,style:g,
link:g,param:g,base:g},t=/^(checked|selected)$/,q=/msie/i.test(navigator.userAgent),x,G,L,O={},T=0,ea=/^-?[\d\.]+$/,ga=/^data-(.+)$/,fa="setAttribute",V="getAttribute",ba=function(){var a=v.createElement("p");a.innerHTML='<a href="#x">x</a><table style="float:left;"></table>';return{hrefExtended:a.getElementsByTagName("a")[0][V]("href")!="#x",autoTbody:a.getElementsByTagName("tbody").length!==0,computedStyle:v.defaultView&&v.defaultView.getComputedStyle,cssFloat:a.getElementsByTagName("table")[0].style.styleFloat?
"styleFloat":"cssFloat",transform:function(){var c=["webkitTransform","MozTransform","OTransform","msTransform","Transform"],j;for(j=0;j<c.length;j++)if(c[j]in a.style)return c[j]}(),classList:"classList"in a}}(),da=/(^\s*|\s*$)/g,W=/\s+/,ja=String.prototype.toString,Z={lineHeight:1,zoom:1,zIndex:1,opacity:1,boxFlex:1,WebkitBoxFlex:1,MozBoxFlex:1},ka=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(da,"")},aa=ba.computedStyle?function(a,c){var j=null,u=v.defaultView.getComputedStyle(a,
"");u&&(j=u[c]);return a.style[c]||j}:q&&n.currentStyle?function(a,c){if(c=="opacity"){var j=100;try{j=a.filters["DXImageTransform.Microsoft.Alpha"].opacity}catch(u){try{j=a.filters("alpha").opacity}catch(B){}}return j/100}j=a.currentStyle?a.currentStyle[c]:null;return a.style[c]||j}:function(a,c){return a.style[c]};if(ba.classList){x=function(a,c){return a.classList.contains(c)};G=function(a,c){a.classList.add(c)};L=function(a,c){a.classList.remove(c)}}else{x=function(a,c){return RegExp("(^|\\s+)"+
c+"(\\s+|$)").test(a.className)};G=function(a,c){a.className=ka(a.className+" "+c)};L=function(a,c){a.className=ka(a.className.replace(RegExp("(^|\\s+)"+c+"(\\s+|$)")," "))}}C.prototype={get:function(a){return this[a]||null},each:function(a,c){return w(this,a,c)},deepEach:function(a,c){return i(this,a,c)},map:function(a,c){var j=[],u,B;for(B=0;B<this.length;B++){u=a.call(this,this[B],B);c?c(u)&&j.push(u):j.push(u)}return j},html:function(a,c){function j(B){w(z(a),function(P){B.appendChild(P)})}var u=
c?n.textContent===undefined?"innerText":"textContent":"innerHTML";return typeof a!=="undefined"?this.empty().each(function(B){if(!c&&S.test(B.tagName))j(B);else try{B[u]=a}catch(P){j(B)}}):this[0]?this[0][u]:""},text:function(a){return this.html(a,1)},append:function(a){return this.each(function(c){w(z(a),function(j){c.appendChild(j)})})},prepend:function(a){return this.each(function(c){var j=c.firstChild;w(z(a),function(u){c.insertBefore(u,j)})})},appendTo:function(a,c){return I.call(this,a,c,function(j,
u){j.appendChild(u)})},prependTo:function(a,c){return I.call(this,a,c,function(j,u){j.insertBefore(u,j.firstChild)})},before:function(a){return this.each(function(c){w(b.create(a),function(j){c[l].insertBefore(j,c)})})},after:function(a){return this.each(function(c){w(b.create(a),function(j){c[l].insertBefore(j,c.nextSibling)})})},insertBefore:function(a,c){return I.call(this,a,c,function(j,u){j[l].insertBefore(u,j)})},insertAfter:function(a,c){return I.call(this,a,c,function(j,u){var B=j.nextSibling;
B?j[l].insertBefore(u,B):j[l].appendChild(u)})},replaceWith:function(a){this.deepEach(o);return this.each(function(c){c.parentNode.replaceChild(b.create(a)[0],c)})},addClass:function(a){a=ja.call(a).split(W);return this.each(function(c){w(a,function(j){j&&!x(c,A(c,j))&&G(c,A(c,j))})})},removeClass:function(a){a=ja.call(a).split(W);return this.each(function(c){w(a,function(j){j&&x(c,A(c,j))&&L(c,A(c,j))})})},hasClass:function(a){a=ja.call(a).split(W);return K(this,function(c){return K(a,function(j){return j&&
x(c,j)})})},toggleClass:function(a,c){a=ja.call(a).split(W);return this.each(function(j){w(a,function(u){if(u)typeof c!=="undefined"?c?G(j,u):L(j,u):x(j,u)?L(j,u):G(j,u)})})},show:function(a){return this.each(function(c){c.style.display=a||""})},hide:function(){return this.each(function(a){a.style.display="none"})},toggle:function(a,c){this.each(function(j){j.style.display=j.offsetWidth||j.offsetHeight?"none":c||""});a&&a();return this},first:function(){return b(this.length?this[0]:[])},last:function(){return b(this.length?
this[this.length-1]:[])},next:function(){return this.related("nextSibling")},previous:function(){return this.related("previousSibling")},parent:function(){return this.related(l)},related:function(a){return this.map(function(c){for(c=c[a];c&&c.nodeType!==1;)c=c[a];return c||0},function(c){return c})},focus:function(){this.length&&this[0].focus();return this},blur:function(){return this.each(function(a){a.blur()})},css:function(a,c,j){if(c===undefined&&typeof a=="string"){c=this[0];if(!c)return null;
if(c===v||c===p){j=c===v?b.doc():b.viewport();return a=="width"?j.width:a=="height"?j.height:""}return(a=E(a))?aa(c,a):null}var u=a;if(typeof a=="string"){u={};u[a]=c}if(q&&u.opacity){u.filter="alpha(opacity="+u.opacity*100+")";u.zoom=a.zoom||1;delete u.opacity}return this.each(function(B,P,M){for(var e in u)if(u.hasOwnProperty(e)){M=u[e];(P=E(e))&&ea.test(M)&&!(P in Z)&&(M+="px");B.style[P]=A(B,M)}})},offset:function(a,c){if(typeof a=="number"||typeof c=="number")return this.each(function(e){var s=
b(e),r=s.css("position"),J=s.offset(),F=r=="relative",R=[parseInt(s.css("left"),10),parseInt(s.css("top"),10)];r=="static"&&s.css("position","relative");isNaN(R[0])&&(R[0]=F?0:e.offsetLeft);isNaN(R[1])&&(R[1]=F?0:e.offsetTop);a!=null&&(e.style.left=a-J.left+R[0]+"px");c!=null&&(e.style.top=c-J.top+R[1]+"px")});if(!this[0])return{top:0,left:0,height:0,width:0};for(var j=this[0],u=j.offsetWidth,B=j.offsetHeight,P=j.offsetTop,M=j.offsetLeft;j=j.offsetParent;){P+=j.offsetTop;M+=j.offsetLeft}return{top:P,
left:M,height:B,width:u}},dim:function(){if(!this.length)return{height:0,width:0};var a=this[0],c=!a.offsetWidth&&!a.offsetHeight?function(B,P){P={position:a.style.position||"",visibility:a.style.visibility||"",display:a.style.display||""};B.first().css({position:"absolute",visibility:"hidden",display:"block"});return P}(this):null,j=a.offsetWidth,u=a.offsetHeight;c&&this.first().css(c);return{height:u,width:j}},attr:function(a,c){var j=this[0];if(typeof a!="string"&&!(a instanceof String)){for(var u in a)a.hasOwnProperty(u)&&
this.attr(u,a[u]);return this}return typeof c=="undefined"?!j?null:H.test(a)?t.test(a)&&typeof j[a]=="string"?true:j[a]:(a=="href"||a=="src")&&ba.hrefExtended?j[V](a,2):j[V](a):this.each(function(B){H.test(a)?B[a]=A(B,c):B[fa](a,A(B,c))})},removeAttr:function(a){return this.each(function(c){t.test(a)?c[a]=false:c.removeAttribute(a)})},val:function(a){return typeof a=="string"?this.attr("value",a):this.length?this[0].value:null},data:function(a,c){var j=this[0],u,B;if(typeof c==="undefined"){if(!j)return null;
u=h(j);if(typeof a==="undefined"){w(j.attributes,function(P){(B=(""+P.name).match(ga))&&(u[d(B[1])]=D(P.value))});return u}else{if(typeof u[a]==="undefined")u[a]=D(this.attr("data-"+(a?a.replace(/([a-z])([A-Z])/g,"$1-$2").toLowerCase():a)));return u[a]}}else return this.each(function(P){h(P)[a]=c})},remove:function(){this.deepEach(o);return this.each(function(a){a[l]&&a[l].removeChild(a)})},empty:function(){return this.each(function(a){for(i(a.childNodes,o);a.firstChild;)a.removeChild(a.firstChild)})},
detach:function(){return this.map(function(a){return a[l].removeChild(a)})},scrollTop:function(a){return m.call(this,null,a,"y")},scrollLeft:function(a){return m.call(this,a,null,"x")}};b.setQueryEngine=function(a){y=a;delete b.setQueryEngine};b.aug=function(a,c){for(var j in a)a.hasOwnProperty(j)&&((c||C.prototype)[j]=a[j])};b.create=function(a){return typeof a=="string"&&a!==""?function(){var c=/^\s*<([^\s>]+)/.exec(a),j=v.createElement("div"),u=[],B=c?f[c[1].toLowerCase()]:null,P=B?B[2]+1:1,M=
B&&B[3],e=l,s=ba.autoTbody&&B&&B[0]=="<table>"&&!/<tbody/i.test(a);for(j.innerHTML=B?B[0]+a+B[1]:a;P--;)j=j.firstChild;if(M&&j&&j.nodeType!==1)j=j.nextSibling;do if((!c||j.nodeType==1)&&(!s||j.tagName.toLowerCase()!="tbody"))u.push(j);while(j=j.nextSibling);w(u,function(r){r[e]&&r[e].removeChild(r)});return u}():a&&a.nodeName&&a.nodeType==1?[a.cloneNode(true)]:[]};b.doc=function(){var a=b.viewport();return{width:Math.max(v.body.scrollWidth,n.scrollWidth,a.width),height:Math.max(v.body.scrollHeight,
n.scrollHeight,a.height)}};b.firstChild=function(a){a=a.childNodes;for(var c=0,j=a&&a.length||0,u;c<j;c++)if(a[c].nodeType===1)u=a[j=c];return u};b.viewport=function(){return{width:q?n.clientWidth:self.innerWidth,height:q?n.clientHeight:self.innerHeight}};b.isAncestor="compareDocumentPosition"in n?function(a,c){return(a.compareDocumentPosition(c)&16)==16}:"contains"in n?function(a,c){return a!==c&&a.contains(c)}:function(a,c){for(;c=c[l];)if(c===a)return true;return false};if(this.Leta)this.Leta.extend({$dom:b});
else this.$dom=b;return b})();
(function(w){function i(k){k=k.relatedTarget;if(!k)return k===null;var g;if(g=k!=this){if(g=k.prefix!="xul"){if(g=!/document/.test(this.toString())){var f;a:for(k=k.parentNode;k!==null;){if(k==this){f=true;break a}k=k.parentNode}g=!f}g=g}g=g}return g}function d(k,g,f){return function(t){for(var q=Leta.isString(k)&&Leta.isFunction(f)?f(k,this):k,x=t.target;x!=this;x=x.parentNode)for(var G=q.length;G--;)if(q[G]==x)return g.apply(x,arguments)}}function h(k){k=o(k);return Q[k]=Q[k]||{}}function o(k,g){return k.__uid=
g&&g+"::"+p++||k.__uid||p++}function D(k,g,f,t,q){return function(x){if(t?t.apply(this,arguments):v?true:x&&x.propertyName=="_on"+f||!x){x=x?A(x||((this.ownerDocument||this.document||this).parentWindow||w).event):null;g.apply(k,Array.prototype.slice.call(arguments,x?0:1).concat(q))}}}function K(k,g,f){return function(t){t=A(t||((this.ownerDocument||this.document||this).parentWindow||w).event);return g.apply(k,[t].concat(f))}}function E(k,g,f,t){var q=g.replace(z,""),x=h(k);x=x[q]||(x[q]={});g=o(f,
g.replace(m,""));if(x[g])return k;var G=l[q];if(G){f=G.condition?D(k,f,q,G.condition):f;q=G.base||q}f=(G=y[q])?K(k,f,t):D(k,f,q,false,t);G=v||G;if(q=="unload"){var L=f;f=function(){I(k,q,f)&&L()}}k[n]&&H(k,G?q:"propertychange",f,true,!G&&q);x[g]=f;f.__uid=g;f.__originalFn=f;return q=="unload"?k:b[o(k)]=k}function I(k,g,f){function t(O){if(f=G[L][O]){delete G[L][O];if(k[n]){L=l[L]?l[L].base:L;O=v||y[L];H(k,O?L:"propertychange",f,false,!O&&L)}}}var q=g.replace(m,""),x=q?q.split("."):[f.__uid],G=h(k),
L=g.replace(z,"");if(!G||!G[L])return k;t(q);for(g=x.length;g--;t(x[g]));return k}function A(k){var g={};if(!k)return g;var f=k.type,t=k.target||k.srcElement;g.preventDefault=A.preventDefault(k);g.stopPropagation=A.stopPropagation(k);g.target=t&&t.nodeType==3?t.parentNode:t;if(~f.indexOf("key"))g.keyCode=k.which||k.keyCode;else if(/click|mouse|menu/i.test(f)){g.rightClick=k.which==3||k.button==2;g.pos={x:0,y:0};if(k.pageX||k.pageY){g.clientX=k.pageX;g.clientY=k.pageY}else if(k.clientX||k.clientY){g.clientX=
k.clientX+document.body.scrollLeft+document.documentElement.scrollLeft;g.clientY=k.clientY+document.body.scrollTop+document.documentElement.scrollTop}/over|out/i.test(f)&&(g.relatedTarget=k.relatedTarget||k[(f=="mouseover"?"from":"to")+"Element"])}for(var q in k)q in g||(g[q]=k[q]);return g}var C={},z=/\..*/,m=/[^\.]*(?=\..*)\.|.*/,Q={},b={},p=1,v=((document||{}).documentElement||{}).addEventListener,n=v?"addEventListener":"attachEvent",l={mouseenter:{base:"mouseover",condition:i},mouseleave:{base:"mouseout",
condition:i},mousewheel:{base:/Firefox/.test(navigator.userAgent)?"DOMMouseScroll":"mousewheel"}},y={click:1,dblclick:1,mouseup:1,mousedown:1,contextmenu:1,mousewheel:1,DOMMouseScroll:1,mouseover:1,mouseout:1,mousemove:1,selectstart:1,selectend:1,keydown:1,keyup:1,keypress:1,orientationchange:1,touchstart:1,touchmove:1,touchend:1,touchcancel:1,gesturestart:1,gesturechange:1,gestureend:1,focus:1,blur:1,change:1,reset:1,select:1,submit:1,load:1,unload:1,beforeunload:1,resize:1,move:1,DOMContentLoaded:1,
readystatechange:1,error:1,abort:1,scroll:1},H=v?function(k,g,f,t){k[t?"addEventListener":"removeEventListener"](g,f,false)}:function(k,g,f,t,q){if(q&&t&&k["_on"+q]===null)k["_on"+q]=0;k[t?"attachEvent":"detachEvent"]("on"+g,f)},S=v?function(k,g,f){var t=document.createEvent(k?"HTMLEvents":"UIEvents");t[k?"initEvent":"initUIEvent"](g,true,true,window,1);f.dispatchEvent(t)}:function(k,g,f){k?f.fireEvent("on"+g,document.createEventObject()):f["_on"+g]++};A.preventDefault=function(k){return function(){if(k.preventDefault)k.preventDefault();
else k.returnValue=false}};A.stopPropagation=function(k){return function(){if(k.stopPropagation)k.stopPropagation();else k.cancelBubble=true}};var N=function(k,g,f,t,q){if(Leta.isObject(g)&&!f)for(var x in g)g.hasOwnProperty(x)&&N(k,x,g[x]);else{x=Leta.isString(f);var G=(x?f:g).split(" ");f=x?d(g,t,q):f;for(var L=G.length;L--;)E(k,G[L],f,Array.prototype.slice.call(arguments,x?4:3))}return k},U=function(k,g,f){var t,q,x,G=Leta.isString(g),L=G&&g.replace(m,""),O=I,T=h(k);L=L&&L.split(".");if(G&&/\s/.test(g)){g=
g.split(" ");for(q=g.length-1;U(k,g[q])&&q--;);return k}x=G?g.replace(z,""):g;if(!T||L||G&&!T[x]){for(t in T)if(T.hasOwnProperty(t))for(q in T[t])for(f=L.length;f--;)T[t].hasOwnProperty(q)&&RegExp("^"+L[f]+"::\\d*(\\..*)?$").test(q)&&O(k,[t,q].join("."));return k}if(Leta.isFunction(f))O(k,x,f);else if(L)O(k,g);else{O=x?O:U;q=G&&x;x=x?f||T[x]||x:T;for(t in x)if(x.hasOwnProperty(t)){O(k,q||t,x[t]);delete x[t]}}return k};this.attachEvent&&N(this,"unload",function(){for(var k in b)if(b.hasOwnProperty(k)){var g=
U(b[k]).__uid;if(g){delete b[g];delete Q[g]}}this.CollectGarbage&&CollectGarbage()});Leta.extend(C,{on:N,off:U,fire:function(k,g,f){var t,q,x,G=g.split(" ");for(q=G.length;q--;){g=G[q].replace(z,"");var L=y[g],O=G[q].replace(m,""),T=h(k)[g];if(O){O=O.split(".");for(t=O.length;t--;)for(x in T)T.hasOwnProperty(x)&&RegExp("^"+O[t]+"::\\d*(\\..*)?$").test(x)&&T[x].apply(k,[false].concat(f))}else if(!f&&k[n])S(L,g,k);else for(t in T)T.hasOwnProperty(t)&&T[t].apply(k,[false].concat(f))}return k}});Leta.extend({event:C})})(window);
(function(){function w(d,h,o){return!d||d&&d==document?null:d==h||d.getAttribute&&d.getAttribute(o)?d:d.parentNode?w(d.parentNode,h,o):null}var i=Leta.event;Leta.extend(i,{bubbleTo:w,dispatch:function(d,h,o,D){if(typeof o=="object"){D=o;o="data-cmd"}i.on(d,h,function(K){var E=w(K.target,d,o);if(E){var I=E.getAttribute(o);D[I]&&D[I].call&&D[I].call(E,K,E)}})}})})(window);
(function(w,i,d){function h(g,f){var t={},q;if(q=g.match(v))t.rotate=C(q[1],f?f.rotate:null);if(q=g.match(n))t.scale=C(q[1],f?f.scale:null);if(q=g.match(l)){t.skewx=C(q[1],f?f.skewx:null);t.skewy=C(q[3],f?f.skewy:null)}if(q=g.match(y)){t.translatex=C(q[1],f?f.translatex:null);t.translatey=C(q[3],f?f.translatey:null)}return t}function o(g){var f="";if("rotate"in g)f+="rotate("+g.rotate+"deg) ";if("scale"in g)f+="scale("+g.scale+") ";if("translatex"in g)f+="translate("+g.translatex+"px,"+g.translatey+
"px) ";if("skewx"in g)f+="skew("+g.skewx+"deg,"+g.skewy+"deg)";return f}function D(g){var f=/rgba?\((\d+),\s*(\d+),\s*(\d+)/.exec(g);return(f?"#"+(16777216|f[1]<<16|f[2]<<8|f[3]).toString(16).slice(1):g).replace(/#(\w)(\w)(\w)$/,"#$1$1$2$2$3$3")}function K(g){return g.replace(/-(.)/g,function(f,t){return t.toUpperCase()})}function E(g){return typeof g=="function"}function I(g,f,t,q,x,G){function L(V){V=V-ea;if(V>O||ga){G=isFinite(G)?G:1;ga?fa&&f(G):f(G);return t&&t()}isFinite(G)?f(T*q(V/O)+x):f(q(V/
O));k(L)}q=q||function(V){return Math.sin(V*Math.PI/2)};var O=g||1E3,T=G-x,ea=+new Date,ga=0,fa=0;k(L);return{stop:function(V){ga=1;fa=V}}}function A(g,f){var t=g.length,q=[],x,G;for(x=0;x<t;++x)q[x]=[g[x][0],g[x][1]];for(G=1;G<t;++G)for(x=0;x<t-G;++x){q[x][0]=(1-f)*q[x][0]+f*q[parseInt(x+1,10)][0];q[x][1]=(1-f)*q[x][1]+f*q[parseInt(x+1,10)][1]}return[q[0][0],q[0][1]]}function C(g,f,t,q,x){return(t=b.exec(g))?(x=parseFloat(t[2]))&&f+(t[1]=="+"?1:-1)*x:parseFloat(g)}function z(g,f){var t=g?t=isFinite(g.length)?
g:[g]:[],q,x=f.complete,G=f.duration,L=f.easing,O=f.bezier,T=[],ea=[],ga=[],fa=[],V,ba;delete f.complete;delete f.duration;delete f.easing;delete f.bezier;if(O){V=f.left;ba=f.top;delete f.right;delete f.bottom;delete f.left;delete f.top}for(q=t.length;q--;){T[q]={};ea[q]={};ga[q]={};if(O){var da=U(t[q],"left"),W=U(t[q],"top"),ja=[C(E(V)?V(t[q]):V||0,parseFloat(da)),C(E(ba)?ba(t[q]):ba||0,parseFloat(W))];fa[q]=E(O)?O(t[q],ja):O;fa[q].push(ja);fa[q].unshift([parseInt(da,10),parseInt(W,10)])}for(var Z in f){da=
U(t[q],Z);var ka;W=E(f[Z])?f[Z](t[q]):f[Z];if(typeof W=="string"&&Q.test(W)&&!Q.test(da))delete f[Z];else{T[q][Z]=Z=="transform"?h(da):typeof W=="string"&&Q.test(W)?D(da).slice(1):parseFloat(da);ea[q][Z]=Z=="transform"?h(W,T[q][Z]):typeof W=="string"&&W.charAt(0)=="#"?D(W).slice(1):C(W,parseFloat(da));typeof W=="string"&&(ka=W.match(p))&&(ga[q][Z]=ka[1])}}}return I(G,function(aa,a,c){for(q=t.length;q--;){if(O){c=A(fa[q],aa);t[q].style.left=c[0]+"px";t[q].style.top=c[1]+"px"}for(var j in f){var u=
aa,B=ga,P=T;a=ea;c=j;var M=q,e=void 0;if(c=="transform"){e={};B=void 0;for(B in P[M][c])e[B]=B in a[M][c]?Math.round(((a[M][c][B]-P[M][c][B])*u+P[M][c][B])*1E3)/1E3:P[M][c][B];a=e}else if(typeof P[M][c]=="string"){u=u;P=P[M][c];a=a[M][c];c=[];M=void 0;e=void 0;for(M=0;M<6;M++){from=Math.min(15,parseInt(P.charAt(M),16));to=Math.min(15,parseInt(a.charAt(M),16));e=Math.floor((to-from)*u+from);e=e>15?15:e<0?0:e;c[M]=e.toString(16)}a="#"+c.join("")}else{e=Math.round(((a[M][c]-P[M][c])*u+P[M][c])*1E3)/
1E3;c in H||(e+=B[M][c]||"px");a=e}j=="transform"?t[q].style[S]=o(a):j=="opacity"&&!N?t[q].style.filter="alpha(opacity="+a*100+")":t[q].style[K(j)]=a}}},x,L)}var m=i.documentElement,Q=/^rgb\(|#/,b=/^([+\-])=([\d\.]+)/,p=/^(?:[\+\-]=)?\d+(?:\.\d+)?(%|in|cm|mm|em|ex|pt|pc|px)$/,v=/rotate\(((?:[+\-]=)?([\-\d\.]+))deg\)/,n=/scale\(((?:[+\-]=)?([\d\.]+))\)/,l=/skew\(((?:[+\-]=)?([\-\d\.]+))deg, ?((?:[+\-]=)?([\-\d\.]+))deg\)/,y=/translate\(((?:[+\-]=)?([\-\d\.]+))px, ?((?:[+\-]=)?([\-\d\.]+))px\)/,H={lineHeight:1,
zoom:1,zIndex:1,opacity:1,transform:1},S=function(){var g=i.createElement("a").style,f=["webkitTransform","MozTransform","OTransform","msTransform","Transform"],t;for(t=0;t<f.length;t++)if(f[t]in g)return f[t]}(),N=typeof i.createElement("a").style.opacity!=="undefined",U=i.defaultView&&i.defaultView.getComputedStyle?function(g,f){f=f=="transform"?S:f;var t=null,q=i.defaultView.getComputedStyle(g,"");q&&(t=q[K(f)]);return g.style[f]||t}:m.currentStyle?function(g,f){f=K(f);if(f=="opacity"){var t=100;
try{t=g.filters["DXImageTransform.Microsoft.Alpha"].opacity}catch(q){try{t=g.filters("alpha").opacity}catch(x){}}return t/100}t=g.currentStyle?g.currentStyle[f]:null;return g.style[f]||t}:function(g,f){return g.style[K(f)]},k=function(){return d.requestAnimationFrame||d.webkitRequestAnimationFrame||d.mozRequestAnimationFrame||d.oRequestAnimationFrame||d.msRequestAnimationFrame||function(g){d.setTimeout(function(){g(+new Date)},10)}}();z.tween=I;z.getStyle=U;z.bezier=A;z.transform=S;z.parseTransform=
h;z.formatTransform=o;if(typeof module!=="undefined")module.exports=z;else w.fx=z})(window.Leta||this,document,window);
(function(w,i){function d(b){return typeof Array.isArray=="function"?Array.isArray(b):Object.prototype.toString.call(b)=="[object Array]"}function h(b){z=b}function o(b,p){if(p==i)p="utf-8";var v=document.createElement("script");v.type="text/javascript";v.charset=p;v.src=b;v.async=true;return v}function D(b,p,v,n){p=C();v=b.jsonpCallback||"callback";var l=b.jsonpCallbackName||"_leta_"+p,y=RegExp("((^|\\?|&)"+v+")=([^&]+)"),H=n.match(y),S=false;if(H)if(H[3]=="?")n=n.replace(y,"$1="+l);else l=H[3];
else n=n+(/\?/.test(n)?"&":"?")+(v+"="+l);w[l]=h;var N=o(n,b.charset);if(typeof N.onreadystatechange!="undefined"){N.event="onclick";N.htmlFor=N.id="_leta_"+p}N.onload=N.onreadystatechange=function(){if(N.readyState&&N.readyState!="complete"&&N.readyState!="loaded"||S)return false;N.onload=N.onreadystatechange=null;N.onclick&&N.onclick();b.success&&b.success(z);z=i;m.removeChild(N);S=true};m.appendChild(N)}function K(b,p,v){return function(){if(b&&b.readyState==4)/^20\d$/.test(b.status)?p(b):v(b)}}
function E(b,p,v){var n=(b.method||"GET").toUpperCase(),l=typeof b=="string"?b:b.url;data=b.stringifyData!==false&&b.data&&typeof b.data!="string"?A.toQueryString(b.data):b.data||null;if(b.type=="jsonp"&&n=="GET"&&data){l=l+(/\?/.test(l)?"&":"?")+data;data=null}if(b.type=="jsonp")return D(b,p,v,l);var y=w.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");y.open(n,l,true);n=b.headers||{};n.Accept=n.Accept||Q.accept[b.type]||Q.accept["*"];if(!b.crossOrigin&&!n["X-Requested-With"])n["X-Requested-With"]=
Q.requestedWith;n["Content-Type"]||(n["Content-Type"]=b.contentType||Q.contentType);for(var H in n)n.hasOwnProperty(H)&&y.setRequestHeader&&y.setRequestHeader(H,n[H]);y.onreadystatechange=K(y,p,v);b.before&&b.before(y);y.send(data);return y}function I(b,p){this.o=b;this.fn=p||function(){};this.success=b.success;this.error=b.error;this.complete=b.complete;this.stringifyData=b.stringifyData;this.url=typeof b=="string"?b:b.url;this.timeout_timer=null;this.timeout=b.timeout;this.type=b.type||"json";this.init(b,
p)}function A(b,p){return new I(b,p)}var C=function(){var b=0;return function(){return b++}}(),z,m=document.getElementsByTagName("head")[0],Q={contentType:"application/x-www-form-urlencoded",accept:{"*":"text/javascript, text/html, application/xml, text/xml, */*",xml:"application/xml, text/xml",html:"text/html",text:"text/plain",json:"application/json, text/javascript",js:"application/javascript, text/javascript"},requestedWith:"XMLHttpRequest"};I.prototype={init:function(b,p){function v(y){l.timeout&&
clearTimeout(l.timeout_timer);l.timeout_timer=null;l.complete&&l.complete(y)}function n(y,H,S){l.error&&l.error(y,H,S);v(y)}var l=this;if(this.timeout)this.timeout_timer=setTimeout(function(){l.abort()},this.timeout);this.request=E(b,function(y){var H=y.responseText;if(H)switch(l.type){case "json":try{y=w.JOSN?w.JSON.parse(H):eval("("+H+")")}catch(S){return n(y,"reponse parse error",S)}break;case "js":y=eval(H);break;case "html":y=H}p&&p(y);l.success&&l.success(y);v(y)},n)},abort:function(){this.request.abort()},
retry:function(){this.init.call(this,this.o,this.fn)}};A.toQueryString=function(b){var p="",v=function(H,S){p+=encodeURIComponent(H)+"="+encodeURIComponent(S)+"&"};if(d(b))for(var n=0;n<b.length;n++)v(b[n].name,b[n].value);else for(var l in b)if(b.hasOwnProperty(l)){var y=b[l];if(d(y))for(n=0;n<y.length;n++)v(l,y[n]);else v(l,y)}return p.replace(/&$/,"").replace(/%20/g,"+")};if(typeof Leta!="undefined")if(Leta.extend)Leta.extend({ajax:A});else Leta.ajax=A;else{w.Leta={};Leta.ajax=A}})(window);
Leta.register(".Dr",function(w){w=w.Class;w=w({initialize:function(h){this.name=h;this.isWaking=false;this.$WAKETODO=[]},$wake:function(){this.isWaking=true},$sleep:function(){this.isWaking=false}});var i=w.extend({initialize:function(h,o){this._super(h);o&&o.call&&o.apply&&o.call(this);this.actors=[];this._observes={}},$wake:function(h){this._super();h!=undefined&&this.$WAKETODO.push(h);this.$firstAct!=undefined&&this.$WAKETODO.push(this.$firstAct);for(h=0;h<this.actors.length;h++){var o=this.actors[h];
o instanceof d&&o.$wake()}for(h=0;h<this.$WAKETODO.length;h++){o=this.$WAKETODO[h];if(typeof o=="string")o=this[o];o.call&&o.apply&&o.call(this)}},$sleep:function(h){this._super();h&&h()},$observe:function(h,o,D){if(this._observes[h.name]==undefined)this._observes[h.name]={};if(this._observes[h.name][o]==undefined)this._observes[h.name][o]=[];this._observes[h.name][o].push(D)}}),d=w.extend({initialize:function(h,o){this._super(h.name);o&&o.call&&o.apply&&o.call(this);this.director=h.director;this.director instanceof
i&&this.director.actors.push(this)},$wake:function(h){this._super();h!=undefined&&this.$WAKETODO.push(h);for(h=0;h<this.$WAKETODO.length;h++){var o=this.$WAKETODO[h];if(typeof o=="string")o=this[o];o.call&&o.apply&&o.call(this)}},$sleep:function(h){this._super();h&&h()},$notifyDirector:function(h){var o=this.director._observes[this.name][h];if(o)for(var D=0;D<o.length;D++)o[D].apply(this,Array.prototype.slice.call(arguments,1))}});this.Director=function(h,o){return this instanceof i?this.init(h,o):
new i(h,o)};this.Actor=function(h,o){return this instanceof d?this.init(h,o):new d(h,o)}});
Leta.register(".util",function(){this.parseUrl=function(w){var i=document.createElement("a");i.href=w;return{source:w,protocol:i.protocol.replace(":",""),host:i.hostname,prot:i.port,query:i.search,file:(i.pathname.match(/\/([^\/?#]+)$/i)||[,""])[1],hash:i.hash.replace("#",""),path:i.pathname.replace(/^([^\/])/,"/$1"),relative:(i.href.match(/tps?:\/\/[^\/]+(.+)/)||[,""])[1],segments:i.pathname.replace(/^\//,"").split("/"),params:function(){for(var d={},h=i.search.replace(/^\?/,"").split("&"),o=h.length,
D=0,K;D<o;D++)if(h[D]){K=h[D].split("=");d[K[0]]=K[1]}return d}()}};this.imgReady=function(){var w=[],i=null,d=function(){for(var h=0;h<w.length;h++)w[h].end?w.splice(h--,1):w[h]();if(!w.length){clearInterval(i);i=null}};return function(h,o,D,K){var E,I,A,C,z,m=new Image;m.src=h;if(m.complete){o.call(m);D&&D.call(m)}else{I=m.width;A=m.height;m.onerror=function(){K&&K.call(m);E.end=true;m=m.onload=m.onerror=null};E=function(){C=m.width;z=m.height;if(C!==I||z!==A||C*z>1024){o.call(m);E.end=true}};E();
m.onload=function(){!E.end&&E();D&&D.call(m);m=m.onload=m.onerror=null};if(!E.end){w.push(E);if(i===null)i=setInterval(d,40)}}}}();this.domReady=function(){function w(){h?document.removeEventListener("DOMContentLoaded",w,true):document.readyState==="complete"&&document.detachEvent("onreadystatechange",w);d()}function i(){if(!o){try{document.documentElement.doScroll("left")}catch(I){window.setTimeout(arguments.callee,15);return}d()}}function d(){if(!o){o=true;for(var I=K.length,A=0;A<I;A++)K[A].call(document)}}
var h=!!document.addEventListener,o=false,D=false,K=[];if(h){document.addEventListener("DOMContentLoaded",w,true);window.addEventListener("load",d,false)}else{document.attachEvent("onreadystatechange",w);window.attachEvent("onload",d);try{D=window.frameElement===null}catch(E){}document.documentElement.doScroll&&D&&i()}return function(I){return o?I.call(document):K.push(I)}}();Leta.extend(this)});
(function(w){var i={easeOut:function(d){return Math.sin(d*Math.PI/2)},easeOutStrong:function(d){return d==1?1:1-Math.pow(2,-10*d)},easeIn:function(d){return d*d},easeInStrong:function(d){return d==0?0:Math.pow(2,10*(d-1))},easeOutBounce:function(d){return d<1/2.75?7.5625*d*d:d<2/2.75?7.5625*(d-=1.5/2.75)*d+0.75:d<2.5/2.75?7.5625*(d-=2.25/2.75)*d+0.9375:7.5625*(d-=2.625/2.75)*d+0.984375},easeInBack:function(d){return d*d*(2.70158*d-1.70158)},easeOutBack:function(d){return(d-=1)*d*(2.70158*d+1.70158)+
1},bounce:function(d){if(d<1/2.75)return 7.5625*d*d;if(d<2/2.75)return 7.5625*(d-=1.5/2.75)*d+0.75;if(d<2.5/2.75)return 7.5625*(d-=2.25/2.75)*d+0.9375;return 7.5625*(d-=2.625/2.75)*d+0.984375},bouncePast:function(d){return d<1/2.75?7.5625*d*d:d<2/2.75?2-(7.5625*(d-=1.5/2.75)*d+0.75):d<2.5/2.75?2-(7.5625*(d-=2.25/2.75)*d+0.9375):2-(7.5625*(d-=2.625/2.75)*d+0.984375)},swingTo:function(d){return(d-=1)*d*(2.70158*d+1.70158)+1},swingFrom:function(d){return d*d*(2.70158*d-1.70158)},elastic:function(d){return-1*
Math.pow(4,-8*d)*Math.sin((d*6-1)*2*Math.PI/2)+1},spring:function(d){return 1-Math.cos(d*4.5*Math.PI)*Math.exp(-d*6)},blink:function(d,h){return Math.round(d*(h||5))%2},pulse:function(d,h){return-Math.cos(d*((h||5)-0.5)*2*Math.PI)/2+0.5},wobble:function(d){return-Math.cos(d*Math.PI*9*d)/2+0.5},sinusoidal:function(d){return-Math.cos(d*Math.PI)/2+0.5},flicker:function(d){d+=(Math.random()-0.5)/5;return i.sinusoidal(d<0?0:d>1?1:d)},mirror:function(d){return d<0.5?i.sinusoidal(d*2):i.sinusoidal(1-(d-
0.5)*2)}};if(typeof Leta!="undefined")if(Leta.extend)Leta.extend({easings:i});else Leta.easings=i;else{w.Leta={};Leta.easings=i}})(window);(function(w){w.$=function(i,d){var h=[];if(!i)return null;if(typeof i!=="string"&&!i.nodeType&&typeof i.length!=="undefined")h=i;else if(i.nodeType===1)h=[i];else if(typeof i==="string")h=/^\s*<([^\s>]+)/.test(i)?w.$dom.create(i):w.$qsa(i,d);return w.$dom(h)}})(Leta);
